apiVersion: v1
kind: Pod
metadata:
  name: liveness-ps-file-probe
spec:
  containers:
  - name: livenesstest-container
    image: joymon/liveness-probe-ps-file:0.6-lts-7.2-nanoserver-1809
    livenessProbe:
      exec:
        command: # this command error out ie return a non zero value if the file is not present. That signal K8s that the pod is not live. 
        - pwsh 
        - -File 
        - c:\liveness.ps1
      initialDelaySeconds: 10
      periodSeconds: 30
  nodeSelector:
    "kubernetes.io/os": windows